mv delivery/apples.txt fruit
mv delivery/bison_burgers.txt meat
mv delivery/brie.txt dairy
mv delivery/broccoli.txt veggies
mv carrot_cake.txt dessert
mv carrots.txt veggies
mv eggo_waffles.txt freezer
mv fage_yogurt.txt dairy
mv fig_bars.txt snax
mv flourless_cake.txt dessert
mv garlic.txt veggies
mv goldfish.txt snax
mv grapples.txt fruit
mv hotdogs.txt meat
mv icecream.txt dessert
mv lamb_ribs.txt meat
mv land_o_lakes_butter.txt dairy
mv lean_cuisine.txt freezer
mv leeks.txt veggies
mv milk.txt dairy
mv mint_milano_cookies.txt dessert
mv onion.txt veggies
mv oreos.txt dessert
mv potatoes.txt veggies
mv salmon_steak.txt meat
mv tiramisu_cake.txt dessert
mv tomatoes.txt fruit
